DROP TABLE IF EXISTS `articles`;
CREATE TABLE `articles` (
	`articleId` INT(5) NOT NULL AUTO_INCREMENT,
	`title` VARCHAR(200) NOT NULL,
	`category` VARCHAR(100) NOT NULL,
	PRIMARY KEY (`articleId`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
DROP TABLE IF EXISTS `employees`;
CREATE TABLE `employees` (
	`id` INT(5) NOT NULL AUTO_INCREMENT,
	`firstName` VARCHAR(200) NOT NULL,
	`middleName` VARCHAR(100) NOT NULL,
	`lastName` VARCHAR(100) NOT NULL,
	`dateOfBirth` DATE NULL DEFAULT NULL,
	`mobilePhone` VARCHAR(20) NULL DEFAULT NULL,
	`homePhone` VARCHAR(20) NULL DEFAULT NULL,
	`city` VARCHAR(100) NULL DEFAULT NULL,
	`address` VARCHAR(100) NULL DEFAULT NULL,
	`postalCode` VARCHAR(100) NULL DEFAULT NULL,
	`gender` VARCHAR(100) NULL DEFAULT NULL,
	`maritalStatus` VARCHAR(100) NULL DEFAULT NULL,
	`typeOfEmployee` VARCHAR(100) NULL DEFAULT NULL,
	`startDate` DATE NULL DEFAULT NULL,
	`endDate` DATE NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1
;
DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
	`record_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(100) NULL DEFAULT NULL,
	`address` VARCHAR(250) NULL DEFAULT NULL,
	`email` VARCHAR(100) NULL DEFAULT NULL,
	PRIMARY KEY (`record_id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1
;
